// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v5.29.1
// source: journal.proto

package durablepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StepStatus is the lifecycle state of a step checkpoint.
//
// Enum value contract (never reuse or renumber):
//
//	0  STEP_STATUS_UNSPECIFIED  — zero value / unknown
//	1  STEP_STATUS_WAITING      — step suspended awaiting external signal or approval
//	2  STEP_STATUS_COMPLETED    — step executed successfully; result is cached
//	3  STEP_STATUS_FAILED       — step returned an error or panicked
type StepStatus int32

const (
	StepStatus_STEP_STATUS_UNSPECIFIED StepStatus = 0
	StepStatus_STEP_STATUS_WAITING     StepStatus = 1
	StepStatus_STEP_STATUS_COMPLETED   StepStatus = 2
	StepStatus_STEP_STATUS_FAILED      StepStatus = 3
)

// Enum value maps for StepStatus.
var (
	StepStatus_name = map[int32]string{
		0: "STEP_STATUS_UNSPECIFIED",
		1: "STEP_STATUS_WAITING",
		2: "STEP_STATUS_COMPLETED",
		3: "STEP_STATUS_FAILED",
	}
	StepStatus_value = map[string]int32{
		"STEP_STATUS_UNSPECIFIED": 0,
		"STEP_STATUS_WAITING":     1,
		"STEP_STATUS_COMPLETED":   2,
		"STEP_STATUS_FAILED":      3,
	}
)

func (x StepStatus) Enum() *StepStatus {
	p := new(StepStatus)
	*p = x
	return p
}

func (x StepStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StepStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_journal_proto_enumTypes[0].Descriptor()
}

func (StepStatus) Type() protoreflect.EnumType {
	return &file_journal_proto_enumTypes[0]
}

func (x StepStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StepStatus.Descriptor instead.
func (StepStatus) EnumDescriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{0}
}

// StepEntry is the binary wire format for a single step checkpoint written to
// journal.log. Using protobuf means:
//   - New fields can be added in future library versions with a new field number.
//   - Unknown fields are preserved on round-trip by the proto runtime.
//   - Old readers silently ignore fields they don't recognise (forward compatibility).
//   - Removing a field leaves the field number reserved, so old data still decodes (backward compatibility).
//
// Field-number contract (never reuse or renumber):
//
//	1  step_id
//	2  seq
//	3  status
//	4  result
//	5  error
//	6  panic_trace
//	7  input_hash
//	8  started_at_ns
//	9  completed_at_ns
type StepEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// step_id is the caller-supplied, run-scoped identifier (durable.StepRecord.StepID).
	StepId string `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	// seq is the 1-based execution order within the parent run.
	Seq int32 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	// status is the lifecycle state of this step.
	Status StepStatus `protobuf:"varint,3,opt,name=status,proto3,enum=durablepb.StepStatus" json:"status,omitempty"`
	// result is the JSON-marshalled output of a completed step.
	// Empty for waiting/failed entries.
	Result []byte `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	// error is the serialised error string for a failed step.
	Error string `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	// panic_trace holds the recovered panic value and stack (if the step panicked).
	PanicTrace string `protobuf:"bytes,6,opt,name=panic_trace,json=panicTrace,proto3" json:"panic_trace,omitempty"`
	// input_hash is a hash of the step input bytes; used to detect input change
	// between retries. Empty in v1 because RunStep has no input parameter.
	InputHash string `protobuf:"bytes,7,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"`
	// started_at_ns is Unix time in nanoseconds when the step function was invoked.
	StartedAtNs int64 `protobuf:"varint,8,opt,name=started_at_ns,json=startedAtNs,proto3" json:"started_at_ns,omitempty"`
	// completed_at_ns is Unix time in nanoseconds when the step reached a terminal state.
	// Zero for waiting entries that have not yet completed.
	CompletedAtNs int64 `protobuf:"varint,9,opt,name=completed_at_ns,json=completedAtNs,proto3" json:"completed_at_ns,omitempty"`
}

func (x *StepEntry) Reset() {
	*x = StepEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_journal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StepEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepEntry) ProtoMessage() {}

func (x *StepEntry) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepEntry.ProtoReflect.Descriptor instead.
func (*StepEntry) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{0}
}

func (x *StepEntry) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepEntry) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *StepEntry) GetStatus() StepStatus {
	if x != nil {
		return x.Status
	}
	return StepStatus_STEP_STATUS_UNSPECIFIED
}

func (x *StepEntry) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *StepEntry) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StepEntry) GetPanicTrace() string {
	if x != nil {
		return x.PanicTrace
	}
	return ""
}

func (x *StepEntry) GetInputHash() string {
	if x != nil {
		return x.InputHash
	}
	return ""
}

func (x *StepEntry) GetStartedAtNs() int64 {
	if x != nil {
		return x.StartedAtNs
	}
	return 0
}

func (x *StepEntry) GetCompletedAtNs() int64 {
	if x != nil {
		return x.CompletedAtNs
	}
	return 0
}

// SignalEntry records an external completion payload for a waiting step.
// Written by CompleteStep; consumed on resume when a WAITING step has a
// matching SignalEntry (signal_id == step_id).
//
// Field-number contract (never reuse or renumber):
//
//	1  signal_id
//	2  payload
//	3  sent_at_ns
type SignalEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// signal_id is the step_id of the waiting step this payload completes.
	SignalId string `protobuf:"bytes,1,opt,name=signal_id,json=signalId,proto3" json:"signal_id,omitempty"`
	// payload is the JSON-encoded result delivered by CompleteStep.
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// sent_at_ns is Unix time in nanoseconds when CompleteStep was called.
	SentAtNs int64 `protobuf:"varint,3,opt,name=sent_at_ns,json=sentAtNs,proto3" json:"sent_at_ns,omitempty"`
}

func (x *SignalEntry) Reset() {
	*x = SignalEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_journal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalEntry) ProtoMessage() {}

func (x *SignalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalEntry.ProtoReflect.Descriptor instead.
func (*SignalEntry) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{1}
}

func (x *SignalEntry) GetSignalId() string {
	if x != nil {
		return x.SignalId
	}
	return ""
}

func (x *SignalEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignalEntry) GetSentAtNs() int64 {
	if x != nil {
		return x.SentAtNs
	}
	return 0
}

// JournalEntry is the top-level frame written to journal.log.
// Using oneof keeps the format extensible for future entry types without
// field number conflicts.
type JournalEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Entry:
	//	*JournalEntry_Step
	//	*JournalEntry_Signal
	Entry isJournalEntry_Entry `protobuf_oneof:"entry"`
}

func (x *JournalEntry) Reset() {
	*x = JournalEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_journal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JournalEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JournalEntry) ProtoMessage() {}

func (x *JournalEntry) ProtoReflect() protoreflect.Message {
	mi := &file_journal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JournalEntry.ProtoReflect.Descriptor instead.
func (*JournalEntry) Descriptor() ([]byte, []int) {
	return file_journal_proto_rawDescGZIP(), []int{2}
}

func (m *JournalEntry) GetEntry() isJournalEntry_Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (x *JournalEntry) GetStep() *StepEntry {
	if x, ok := x.GetEntry().(*JournalEntry_Step); ok {
		return x.Step
	}
	return nil
}

func (x *JournalEntry) GetSignal() *SignalEntry {
	if x, ok := x.GetEntry().(*JournalEntry_Signal); ok {
		return x.Signal
	}
	return nil
}

type isJournalEntry_Entry interface {
	isJournalEntry_Entry()
}

type JournalEntry_Step struct {
	Step *StepEntry `protobuf:"bytes,1,opt,name=step,proto3,oneof"`
}

type JournalEntry_Signal struct {
	Signal *SignalEntry `protobuf:"bytes,2,opt,name=signal,proto3,oneof"`
}

func (*JournalEntry_Step) isJournalEntry_Entry() {}

func (*JournalEntry_Signal) isJournalEntry_Entry() {}

var File_journal_proto protoreflect.FileDescriptor

var file_journal_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x64, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x70, 0x62, 0x22, 0x9f, 0x02, 0x0a, 0x09, 0x53,
	0x74, 0x65, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x74, 0x65, 0x70,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x65, 0x70, 0x49,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x73, 0x65, 0x71, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x64, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x70, 0x62, 0x2e,
	0x53, 0x74, 0x65, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x61, 0x6e, 0x69, 0x63, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x6e, 0x69, 0x63, 0x54, 0x72, 0x61, 0x63,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x22, 0x0a, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x6e,
	0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x4e, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x5f, 0x6e, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x4e, 0x73, 0x22, 0x62, 0x0a, 0x0b,
	0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x1c, 0x0a, 0x0a, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x5f, 0x6e, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x4e, 0x73,
	0x22, 0x75, 0x0a, 0x0c, 0x4a, 0x6f, 0x75, 0x72, 0x6e, 0x61, 0x6c, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x2a, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x64, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x74, 0x65, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x48, 0x00, 0x52, 0x04, 0x73, 0x74, 0x65, 0x70, 0x12, 0x30, 0x0a, 0x06,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64,
	0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x70, 0x62, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x48, 0x00, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x42, 0x07,
	0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x2a, 0x75, 0x0a, 0x0a, 0x53, 0x74, 0x65, 0x70, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x54, 0x45, 0x50, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x54, 0x45, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x57, 0x41, 0x49, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x53,
	0x54, 0x45, 0x50, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c,
	0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x45, 0x50, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x42, 0x2f,
	0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x69, 0x63, 0x65, 0x6e, 0x76, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x2d,
	0x67, 0x6f, 0x2f, 0x70, 0x62, 0x3b, 0x64, 0x75, 0x72, 0x61, 0x62, 0x6c, 0x65, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_journal_proto_rawDescOnce sync.Once
	file_journal_proto_rawDescData = file_journal_proto_rawDesc
)

func file_journal_proto_rawDescGZIP() []byte {
	file_journal_proto_rawDescOnce.Do(func() {
		file_journal_proto_rawDescData = protoimpl.X.CompressGZIP(file_journal_proto_rawDescData)
	})
	return file_journal_proto_rawDescData
}

var file_journal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_journal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_journal_proto_goTypes = []interface{}{
	(StepStatus)(0),      // 0: durablepb.StepStatus
	(*StepEntry)(nil),    // 1: durablepb.StepEntry
	(*SignalEntry)(nil),  // 2: durablepb.SignalEntry
	(*JournalEntry)(nil), // 3: durablepb.JournalEntry
}
var file_journal_proto_depIdxs = []int32{
	0, // 0: durablepb.StepEntry.status:type_name -> durablepb.StepStatus
	1, // 1: durablepb.JournalEntry.step:type_name -> durablepb.StepEntry
	2, // 2: durablepb.JournalEntry.signal:type_name -> durablepb.SignalEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_journal_proto_init() }
func file_journal_proto_init() {
	if File_journal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_journal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StepEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_journal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignalEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_journal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JournalEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_journal_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*JournalEntry_Step)(nil),
		(*JournalEntry_Signal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_journal_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_journal_proto_goTypes,
		DependencyIndexes: file_journal_proto_depIdxs,
		EnumInfos:         file_journal_proto_enumTypes,
		MessageInfos:      file_journal_proto_msgTypes,
	}.Build()
	File_journal_proto = out.File
	file_journal_proto_rawDesc = nil
	file_journal_proto_goTypes = nil
	file_journal_proto_depIdxs = nil
}
